# Exercise on Functions:

# Task-1 Unit Conversion

In [1]:
def convert_length(value, unit):
    """
    This function converts length between meters and feet.

    Arguments:
    value (float): The numerical value that needs to be converted.
    unit (str): The type of conversion ('m_to_ft' for meters to feet, 'ft_to_m' for feet to meters).

    Returns:
    float: The converted length value.

    Raises:
    ValueError: If an incorrect unit type is given.
    """
    if unit == 'm_to_ft':
        return value * 3.28084  # Meters to feet conversion
    elif unit == 'ft_to_m':
        return value / 3.28084  # Feet to meters conversion
    else:
        raise ValueError("Invalid conversion unit for length.")  # Raise error for invalid unit

def convert_weight(value, unit):
    """
    This function converts weight between kilograms and pounds.

    Arguments:
    value (float): The numerical value to convert.
    unit (str): The conversion type ('kg_to_lbs' for kg to lbs, 'lbs_to_kg' for lbs to kg).

    Returns:
    float: The converted weight value.

    Raises:
    ValueError: If the conversion unit is invalid.
    """
    if unit == 'kg_to_lbs':
        return value * 2.20462  # Convert kilograms to pounds
    elif unit == 'lbs_to_kg':
        return value / 2.20462  # Convert pounds to kilograms
    else:
        raise ValueError("Invalid conversion unit for weight.")  # Handle incorrect input

def convert_volume(value, unit):
    """
    This function converts volume between liters and gallons.

    Arguments:
    value (float): The value that needs to be converted.
    unit (str): The conversion type ('L_to_gal' for liters to gallons, 'gal_to_L' for gallons to liters).

    Returns:
    float: The converted volume value.

    Raises:
    ValueError: If the conversion unit is invalid.
    """
    if unit == 'L_to_gal':
        return value * 0.264172  # Convert liters to gallons
    elif unit == 'gal_to_L':
        return value / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Invalid conversion unit for volume.")  # Handle incorrect input

def main():
    """
    The main function of the program.
    It allows users to choose a conversion type, input a value, and get the converted result.
    """
    print("Welcome to the Unit Converter!")  # Introduction message
    print("Choose from the following conversions:")
    print("1. Length (meters to feet OR feet to meters)")
    print("2. Weight (kilograms to pounds OR pounds to kilograms)")
    print("3. Volume (liters to gallons OR gallons to liters)")

    try:
        # Ask user for the conversion type
        conversion_type = int(input("Enter 1, 2, or 3 to choose conversion type: "))
        value = float(input("Enter the value you want to convert: "))  # Get the number for conversion

        if conversion_type == 1:
            unit = input("Specify conversion ('m_to_ft' or 'ft_to_m'): ")
            result = convert_length(value, unit)  # Call length conversion function
        elif conversion_type == 2:
            unit = input("Specify conversion ('kg_to_lbs' or 'lbs_to_kg'): ")
            result = convert_weight(value, unit)  # Call weight conversion function
        elif conversion_type == 3:
            unit = input("Specify conversion ('L_to_gal' or 'gal_to_L'): ")
            result = convert_volume(value, unit)  # Call volume conversion function
        else:
            print("Error: Invalid choice. Please enter 1, 2, or 3.")
            return  # Exit function on invalid input

        print(f"Converted value: {result}")  # Output the result

    except ValueError as e:
        print(f"Invalid input: {e}")  # Handle incorrect data entry

# Execute the unit converter program
main()


Welcome to the Unit Converter!
Choose from the following conversions:
1. Length (meters to feet OR feet to meters)
2. Weight (kilograms to pounds OR pounds to kilograms)
3. Volume (liters to gallons OR gallons to liters)
Enter 1, 2, or 3 to choose conversion type: 2
Enter the value you want to convert: 10
Specify conversion ('kg_to_lbs' or 'lbs_to_kg'): kg_to_lbs
Converted value: 22.0462


# Task-2 Math Operation on List of Numbers

In [2]:
def calculate_sum(numbers):
    """
    Computes and returns the sum of a list of numbers.

    Arguments:
    numbers (list): A list containing numerical values.

    Returns:
    float: The total sum of the numbers in the list.
    """
    return sum(numbers)  # Adds all elements together

def calculate_average(numbers):
    """
    Computes and returns the average of a given list of numbers.

    Arguments:
    numbers (list): A list containing numerical values.

    Returns:
    float: The average value of the list.

    Note:
    If the list is empty, a ZeroDivisionError will be raised.
    """
    return sum(numbers) / len(numbers)  # Computes the mean

def find_maximum(numbers):
    """
    Determines and returns the highest number in a given list.

    Arguments:
    numbers (list): A list of numerical values.

    Returns:
    float: The maximum value found in the list.
    """
    return max(numbers)  # Identifies the largest number

def find_minimum(numbers):
    """
    Determines and returns the smallest number in a given list.

    Arguments:
    numbers (list): A list of numerical values.

    Returns:
    float: The minimum value found in the list.
    """
    return min(numbers)  # Identifies the smallest number

def main():
    """
    The main function that runs the interactive program.
    It allows users to choose an operation and input numbers.
    """
    print("Welcome to the Mathematical Operations Program!")  # Program introduction
    print("Available operations:")
    print("1. Calculate Sum")
    print("2. Calculate Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        # Prompt user for choice
        operation = int(input("Enter 1, 2, 3, or 4 to select an operation: "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))  # User enters numbers

        # Perform selected operation
        if operation == 1:
            print(f"The sum of the numbers is: {calculate_sum(numbers)}")
        elif operation == 2:
            print(f"The average of the numbers is: {calculate_average(numbers)}")
        elif operation == 3:
            print(f"The highest number is: {find_maximum(numbers)}")
        elif operation == 4:
            print(f"The lowest number is: {find_minimum(numbers)}")
        else:
            print("Invalid selection. Please enter a number between 1 and 4.")

    except ValueError as e:
        print(f"Invalid input: {e}. Please enter valid numbers.")  # Error handling
    except ZeroDivisionError:
        print("Error: Cannot compute the average of an empty list.")  # Handling division by zero

# Execute the program
main()


Welcome to the Mathematical Operations Program!
Available operations:
1. Calculate Sum
2. Calculate Average
3. Find Maximum
4. Find Minimum
Enter 1, 2, 3, or 4 to select an operation: 1
Enter numbers separated by spaces: 20 10
The sum of the numbers is: 30.0


# Exercise on List Manipulation:

In [3]:
def extract_every_other(lst):
    """
    This function returns every other element from the given list.

    Parameters:
    - lst (list): The input list of elements.

    Returns:
    - list: A new list containing elements at alternate positions.
    """
    return lst[::2]  # Picks elements at even indexes (0, 2, 4, ...).

# Function call example
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # Expected output: [1, 3, 5]


[1, 3, 5]


In [4]:
def get_sublist(lst, start, end):
    """
    This function extracts a portion of a list based on the given start and end indexes.

    Parameters:
    - lst (list): The original list.
    - start (int): The index where extraction begins.
    - end (int): The index where extraction stops.

    Returns:
    - list: A sublist containing elements from start to end (inclusive).
    """
    return lst[start:end+1]  # Returns a sliced list including the end index.

# Function call example
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # Expected output: [3, 4, 5]


[3, 4, 5]


In [5]:
def reverse_list(lst):
    """
    This function returns the reversed version of the given list.

    Parameters:
    - lst (list): The list to be reversed.

    Returns:
    - list: A new list with elements in reverse order.
    """
    return lst[::-1]  # Uses slicing to reverse the list.

# Function call example
print(reverse_list([1, 2, 3, 4, 5]))  # Expected output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


In [6]:
def remove_first_last(lst):
    """
    This function removes the first and last elements from a given list.

    Parameters:
    - lst (list): The original list.

    Returns:
    - list: A new list excluding the first and last elements.
    """
    return lst[1:-1]  # Returns a sliced list without the first and last items.

# Function call example
print(remove_first_last([1, 2, 3, 4, 5]))  # Expected output: [2, 3, 4]


[2, 3, 4]


In [7]:
def get_first_n(lst, n):
    """
    This function extracts the first n elements from the provided list.

    Parameters:
    - lst (list): The original list.
    - n (int): The number of elements to be extracted.

    Returns:
    - list: A new list containing the first n elements.
    """
    return lst[:n]  # Extracts the first n elements using slicing.

# Function call example
print(get_first_n([1, 2, 3, 4, 5], 3))  # Expected output: [1, 2, 3]


[1, 2, 3]


In [8]:
def get_last_n(lst, n):
    """
    This function extracts the last n elements from the given list using slicing.

    Parameters:
    - lst (list): The original list.
    - n (int): The number of elements to extract from the end.

    Returns:
    - list: A new list containing the last n elements.
    """
    return lst[-n:]  # Uses slicing to extract the last n elements.

# Function call example
print(get_last_n([1, 2, 3, 4, 5], 2))  # Expected output: [4, 5]


[4, 5]


In [9]:
def reverse_skip(lst):
    """
    This function extracts every second element from the list starting from the second-to-last element, moving in reverse.

    Parameters:
    - lst (list): The original list.

    Returns:
    - list: A new list containing every second element, starting from the second-to-last, moving backwards.
    """
    return lst[-2::-2]  # Slices the list to get every second element in reverse order.

# Function call example
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Expected output: [5, 3, 1]


[5, 3, 1]


# Exercise on Nested List

In [10]:
def flatten(lst):
    """
    This function flattens a nested list into a single list by recursively unpacking inner lists.

    Parameters:
    - lst (list): The nested list that needs to be flattened.

    Returns:
    - list: A new, flattened list containing all elements from the nested list.
    """
    flat_list = []  # Start with an empty list to accumulate the flattened elements.
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call flatten recursively.
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)  # Directly append non-list items to the result.
    return flat_list

# Function call example
print(flatten([[1, 2], [3, [4, 5]], 6]))  # Expected output: [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


In [11]:
def access_nested_element(lst, indices):
    """
    This function extracts a specific element from a nested list using a list of indices.

    Parameters:
    - lst (list): The nested list.
    - indices (list): A list of indices specifying the path to the element.

    Returns:
    - any: The element located at the specified indices.
    """
    for index in indices:  # Traverse through each index in the indices list.
        lst = lst[index]  # Update lst to the element at the current index.
    return lst  # Return the located element.

# Function call example
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))  # Expected output: 6


6


In [12]:
def sum_nested(lst):
    """
    This function calculates the sum of all numbers within a nested list by first flattening the list.

    Parameters:
    - lst (list): The nested list containing numbers.

    Returns:
    - float: The sum of all elements after flattening the list.
    """
    return sum(flatten(lst))  # Flatten the list and compute the sum of all its elements.

# Function call example
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Expected output: 21


21


In [13]:
def remove_element(lst, elem):
    """
    This function removes all occurrences of a specific element from a nested list.

    Parameters:
    - lst (list): The nested list.
    - elem (any): The element to be removed.

    Returns:
    - list: The modified list with the element removed.
    """
    # Recursively iterate through the list and remove elem.
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

# Function call example
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Expected output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


In [14]:
def find_max(lst):
    """
    This function finds the maximum element in a nested list by flattening it first.

    Parameters:
    - lst (list): The nested list from which the maximum element is to be found.

    Returns:
    - float: The maximum element after flattening the list.
    """
    # Flatten the list and then find the maximum element
    return max(flatten(lst))

# Function call example
print(find_max([[1, 2], [3, [4, 5]], 6]))  # Expected output: 6


6


In [15]:
def count_occurrences(lst, elem):
    """
    This function counts how many times a specific element appears in a nested list by flattening it first.

    Parameters:
    - lst (list): The nested list to search through.
    - elem (any): The element whose occurrences are to be counted.

    Returns:
    - int: The number of occurrences of the element in the flattened list.
    """
    # Flatten the list and then count how many times elem appears
    return flatten(lst).count(elem)

# Function call example
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Expected output: 3


3


In [16]:
def deep_flatten(lst):
    """
    This function flattens a deeply nested list into a single list by recursively flattening it.

    Parameters:
    - lst (list): The deeply nested list to be flattened.

    Returns:
    - list: A single list that contains all the elements from the deeply nested list.
    """
    # Flatten the nested list using the helper function 'flatten'
    return flatten(lst)

# Function call example
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Expected output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
def average_nested(lst):
    """
    This function calculates the average of all elements in a nested list by first flattening it.

    Parameters:
    - lst (list): The nested list whose elements are to be averaged.

    Returns:
    - float: The average of all elements in the flattened list.
    """
    # Flatten the nested list and compute the average using sum and length
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)

# Function call example
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Expected output: 3.5


3.5


# Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))  # Uninitialized array with random values
print("Empty 2x2 Array:\n", empty_array)
print("---------------")

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))  # 4x2 array filled with ones
print("All Ones 4x2 Array:\n", ones_array)
print("---------------")

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # 3x3 array filled with 5
print("Array Filled with Value 5:\n", fill_value_array)
print("---------------")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])  # Initial given array
zeros_like_array = np.zeros_like(given_array)  # Zeros array matching shape
print("Zeros Array with Same Shape as Given Array:\n", zeros_like_array)
print("---------------")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)  # Ones array matching shape
print("Ones Array with Same Shape as Given Array:\n", ones_like_array)
print("---------------")

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]  # Python list
numpy_array = np.array(new_list)  # List converted to NumPy array
print("Converted NumPy Array from List:\n", numpy_array)


Empty 2x2 Array:
 [[2.0742587e-316 0.0000000e+000]
 [4.9406565e-324            nan]]
---------------
All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
Array Filled with Value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
---------------
Zeros Array with Same Shape as Given Array:
 [[0 0]
 [0 0]]
---------------
Ones Array with Same Shape as Given Array:
 [[1 1]
 [1 1]]
---------------
Converted NumPy Array from List:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [19]:
import numpy as np

# 1. Create an array that ranges from 10 to 49
range_array = np.arange(10, 50)
print("Array with Values from 10 to 49:\n", range_array)
print("---------------")

# 2. Generate a 3x3 array with numbers from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with Values 0 to 8:\n", matrix_3x3)
print("---------------")

# 3. Generate a 3x3 identity matrix (diagonal elements are 1)
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
print("---------------")

# 4. Generate a random array of 30 values and calculate its average
random_array = np.random.random(30)
mean_value = random_array.mean()  # Compute the average of the random values
print("Random Array of Size 30:\n", random_array)
print("Mean of Random Array:", mean_value)
print("---------------")

# 5. Create a 10x10 random array and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()  # Extract the minimum value from the array
max_value = random_10x10.max()  # Extract the maximum value from the array
print("10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("---------------")

# 6. Create a zero-filled array of size 10 and replace the 5th value with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Set the 5th element (at index 4) to 1
print("Zero Array with 5th Element Replaced:\n", zero_array)
print("---------------")

# 7. Reverse the elements of the array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]  # Flip the array
print("Reversed Array:\n", reversed_arr)
print("---------------")

# 8. Create a 2D array with 1s on the edges and 0s inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0  # Set the internal values to 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)
print("---------------")

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Create alternating 1s in certain cells
checkerboard[::2, 1::2] = 1  # Continue with alternating pattern
print("8x8 Checkerboard Pattern:\n", checkerboard)


Array with Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array of Size 30:
 [0.9157436  0.50193078 0.41182855 0.35000973 0.00187648 0.31318816
 0.82877937 0.46952023 0.06822394 0.47106296 0.10617087 0.05816773
 0.15757181 0.68295035 0.79601068 0.16061389 0.68979721 0.13620678
 0.98040101 0.46682643 0.5945786  0.13433113 0.3209735  0.60252165
 0.56536979 0.07967357 0.40486905 0.69434048 0.84266195 0.76397209]
Mean of Random Array: 0.4523390792031783
---------------
10x10 Random Array:
 [[0.02221333 0.44776743 0.26222252 0.41943487 0.29674333 0.09931957
  0.20427776 0.73665707 0.44316527 0.05990184]
 [0.01556806 0.43935539 0.00825475 0.61120463 0.0247982  0.45335738
  0.0980834  0.91053125 0.5675049  0.77157586]
 [0.74

# Problem - 3: Array Operations:

In [20]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the arrays element-wise
add_result = x + y  # Add corresponding elements of x and y
print("Addition of x and y:\n", add_result)
print("---------------")

# 2. Subtract the arrays element-wise
subtract_result = x - y  # Subtract corresponding elements of x and y
print("Subtraction of x and y:\n", subtract_result)
print("---------------")

# 3. Multiply the array by 2
multiply_result = x * 2  # Element-wise multiplication of x by 2
print("Multiplication of x by 2:\n", multiply_result)
print("---------------")

# 4. Find the square of each element in x
square_result = np.square(x)  # Compute the square of each element in x
print("Square of Each Element in x:\n", square_result)
print("---------------")

# 5. Compute the dot product of the arrays
dot_vw = np.dot(v, w)  # Dot product between vectors v and w
dot_xv = np.dot(x, v)  # Dot product of matrix x with vector v
dot_xy = np.dot(x, y)  # Dot product between matrices x and y
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:\n", dot_xy)
print("---------------")

# 6. Concatenate the arrays x and y along rows, and v and w along columns
concatenate_rows = np.concatenate((x, y), axis=0)  # Stack x and y along rows (axis=0)
concatenate_columns = np.vstack((v, w))  # Stack v and w vertically
print("Concatenate x and y along rows:\n", concatenate_rows)
print("Concatenate v and w along columns:\n", concatenate_columns)
print("---------------")

# 7. Try to concatenate x and v (results in an error)
try:
    concatenate_xv = np.concatenate((x, v))  # Attempt concatenation of x and v
except ValueError as e:
    print("Error:", e)  # Handle the error and print the message
    print("Explanation: Arrays x (2x2) and v (2,) cannot be concatenated due to incompatible shapes.")


Addition of x and y:
 [[ 6  8]
 [10 13]]
---------------
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
---------------
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of Each Element in x:
 [[ 1  4]
 [ 9 25]]
---------------
Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]
---------------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Arrays x (2x2) and v (2,) cannot be concatenated due to incompatible shapes.


# Problem - 4: Matrix Operations:

In [21]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Show that A.A^-1 = I (Identity Matrix Proof)
A_inv = np.linalg.inv(A)  # Calculate the inverse of matrix A
identity_check = np.dot(A, A_inv)  # Multiply A by its inverse to get the identity matrix
print("A.A^-1:\n", identity_check)
print("---------------")

# 2. Show that AB != BA (Matrix Multiplication is not Commutative)
AB = np.dot(A, B)  # Matrix multiplication of A and B
BA = np.dot(B, A)  # Matrix multiplication of B and A
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB != BA?", not np.array_equal(AB, BA))  # Compare AB and BA to check if they are different
print("---------------")

# 3. Show that (AB)^T = B^T A^T (Transpose of Product Rule)
AB_transpose = AB.T  # Compute the transpose of the product AB
B_transpose_A_transpose = np.dot(B.T, A.T)  # Multiply the transposes of B and A
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("Is (AB)^T == B^T A^T?", np.array_equal(AB_transpose, B_transpose_A_transpose))  # Check if the property holds
print("---------------")

# Solve the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix for the system
B_eq = np.array([-1, -3, 9])  # Right-hand side constants
print("---------------")

# Solve using inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)  # Solve for X using the inverse of A_eq
print("Solution using Inverse Method:", X)
print("---------------")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)  # Solve the system using numpy's efficient solver
print("Solution using np.linalg.solve:", X_solve)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB != BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T == B^T A^T? True
---------------
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

In [22]:
import time
import numpy as np

# Function to measure time taken for an operation
def measure_time(func, *args):
    start_time = time.time()  # Capture start time
    func(*args)  # Execute the passed function
    end_time = time.time()  # Capture end time
    return end_time - start_time  # Return the elapsed time in seconds

# 1. Element-wise Addition
def elementwise_addition_python(list1, list2):
    return [a + b for a, b in zip(list1, list2)]  # Element-wise addition using Python lists

def elementwise_addition_numpy(array1, array2):
    return array1 + array2  # Element-wise addition using NumPy arrays

# 2. Element-wise Multiplication
def elementwise_multiplication_python(list1, list2):
    return [a * b for a, b in zip(list1, list2)]  # Element-wise multiplication using Python lists

def elementwise_multiplication_numpy(array1, array2):
    return array1 * array2  # Element-wise multiplication using NumPy arrays

# 3. Dot Product
def dot_product_python(list1, list2):
    return sum(a * b for a, b in zip(list1, list2))  # Dot product using Python lists

def dot_product_numpy(array1, array2):
    return np.dot(array1, array2)  # Dot product using NumPy arrays

# 4. Matrix Multiplication
def matrix_multiplication_python(matrix1, matrix2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]  # Matrix multiplication with Python lists
    return result

def matrix_multiplication_numpy(matrix1, matrix2):
    return np.dot(matrix1, matrix2)  # Matrix multiplication with NumPy arrays

# Initialize data
size = 1000000  # Set the size for element-wise operations
list1 = list(range(size))  # Create list1 from 0 to size-1
list2 = list(range(size, 2 * size))  # Create list2 from size to 2*size-1
array1 = np.arange(size)  # Create NumPy array1 from 0 to size-1
array2 = np.arange(size, 2 * size)  # Create NumPy array2 from size to 2*size-1

matrix_size = 1000  # Define the matrix size for matrix operations
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]  # Matrix1 with size matrix_size x matrix_size
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]  # Matrix2 with size matrix_size x matrix_size
np_matrix1 = np.array(matrix1)  # Convert matrix1 to a NumPy array
np_matrix2 = np.array(matrix2)  # Convert matrix2 to a NumPy array

# Measure time for each operation
print("1. Element-wise Addition:")
time_python_add = measure_time(elementwise_addition_python, list1, list2)
time_numpy_add = measure_time(elementwise_addition_numpy, array1, array2)
print(f"Python Lists: {time_python_add:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_add:.6f} seconds")

print("\n2. Element-wise Multiplication:")
time_python_mul = measure_time(elementwise_multiplication_python, list1, list2)
time_numpy_mul = measure_time(elementwise_multiplication_numpy, array1, array2)
print(f"Python Lists: {time_python_mul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_mul:.6f} seconds")

print("\n3. Dot Product:")
time_python_dot = measure_time(dot_product_python, list1, list2)
time_numpy_dot = measure_time(dot_product_numpy, array1, array2)
print(f"Python Lists: {time_python_dot:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_dot:.6f} seconds")

print("\n4. Matrix Multiplication:")
time_python_matmul = measure_time(matrix_multiplication_python, matrix1, matrix2)
time_numpy_matmul = measure_time(matrix_multiplication_numpy, np_matrix1, np_matrix2)
print(f"Python Lists: {time_python_matmul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_matmul:.6f} seconds")


1. Element-wise Addition:
Python Lists: 0.050895 seconds
NumPy Arrays: 0.002286 seconds

2. Element-wise Multiplication:
Python Lists: 0.044301 seconds
NumPy Arrays: 0.001092 seconds

3. Dot Product:
Python Lists: 0.049180 seconds
NumPy Arrays: 0.000879 seconds

4. Matrix Multiplication:
Python Lists: 90.606372 seconds
NumPy Arrays: 0.815162 seconds
